apiVersion: v1
kind: Service
metadata:
  name: "hello-service"
  namespace: default
  labels: 
    app: "hello"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "hello"
  type: "LoadBalancer"
  loadBalancerIP: ""



